Environment:
    cluster: Minerva
    server: 
project_directory: /sc/orga//scratch/lohy01/RNAseq_Projects/
Short-read_aligners:
    tophat2: tophat/2.0.9
    bowtie2: bowtie2/2.1.0
    STAR: rna-star/2.3.0e
genomes: 
    mouse: 
        rRNApath: /sc/orga/work/lohy01/Databases/Bowtie2Index/MM10/rRNA.bed
        tophat2:  
            gtf: /sc/orga/work/lohy01/Databases/Bowtie2Index/MM10/gencode.vM2.annotation.gtf
            index: /sc/orga/work/lohy01/Databases/Bowtie2Index/MM10/genome
        exonicPath: 
        intronicPath: 
        intragenicPath:
        intergenicPath:
        STAR:
            path: 
    hg19_ERCC: 
        rRNApath: 
        tophat2:  
            gtf: 
            index: 
        exonicPath: 
        intronicPath:
        intragenicPath:
        intergenicPath:
        STAR:
            path:
    mm9: 
        rRNApath: 
        tophat2:  
            gtf: 
            index: 
        exonicPath: 
        intronicPath: 
        intragenicPath:
        intergenicPath:
        STAR:
            path: 
